cacheFolder: ./.yarn/cache

checksumBehavior: update

cloneConcurrency: 1

compressionLevel: mixed

enableGlobalCache: true

enableImmutableInstalls: false

enableInlineBuilds: false

enableScripts: false

networkConcurrency: 1

nmHoistingLimits: workspaces

nmSelfReferences: true

nodeLinker: node-modules

taskPoolConcurrency: 2
